[package]
name = "incident-recognition"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "1.5.4"
aws-sdk-rekognition = "1.37.0"
aws-sdk-s3 = { version = "1.40.0", features = ["rt-tokio"]}
aws-types = "1.3.3"
tokio = {version="1.38.0", features = ["full"]}
